# Generated by Django 3.1.4 on 2020-12-02 16:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_news', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='uploads')),
                ('slug', models.CharField(max_length=130)),
                ('Repoter_name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('publish', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 22, 47, 24, 200934))),
            ],
        ),
        migrations.CreateModel(
            name='catagory_of_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='signup_information',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=255)),
                ('User_phone', models.CharField(max_length=255)),
                ('User_email', models.CharField(max_length=255)),
                ('User_Date_of_birth', models.DateField(max_length=255)),
                ('User_pass', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_email', models.CharField(max_length=255)),
                ('user_image', models.ImageField(default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='News_Comment',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('postID', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 2, 22, 47, 24, 201933))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsApp.news_comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.add_news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='add_news',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsApp.catagory_of_news'),
        ),
    ]
