# Generated by Django 3.1.4 on 2020-12-02 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20201202_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_news',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 0, 10, 37, 204057)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 0, 10, 37, 205056)),
        ),
        migrations.CreateModel(
            name='News_Comment_new',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user', models.CharField(max_length=255)),
                ('postID', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 0, 10, 37, 206055))),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsApp.news_comment_new')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsApp.add_news')),
            ],
        ),
    ]
