# Generated by Django 3.1.4 on 2020-12-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_auto_20201203_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_comment_new',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='news_comment_new',
            name='post',
        ),
        migrations.AlterField(
            model_name='add_news_new',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 18, 28, 55, 929129)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 18, 28, 55, 931127)),
        ),
        migrations.DeleteModel(
            name='like_new',
        ),
        migrations.DeleteModel(
            name='News_Comment_new',
        ),
    ]
