# Generated by Django 3.1.4 on 2020-12-03 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0008_auto_20201203_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup_information',
        ),
        migrations.AlterField(
            model_name='add_news_new',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 18, 34, 41, 790893)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 18, 34, 41, 792892)),
        ),
    ]
