# Generated by Django 3.1.4 on 2020-12-03 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0013_auto_20201203_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_settings',
            name='user',
        ),
        migrations.DeleteModel(
            name='upload_image',
        ),
        migrations.AlterField(
            model_name='add_news_new',
            name='publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 22, 42, 57, 50128)),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='time_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 22, 42, 57, 53126)),
        ),
        migrations.DeleteModel(
            name='profile_settings',
        ),
    ]
